### PR TITLE
Ignore tests when the app version is too old

### LINKED ISSUE #24: Feature Request: Filter tests by comparing test and app version tags
@davidchall Hope you are well. :smile: I had an idea for a feature I wanted to run by you. 

When dealing with a large collection of regression test input files and many different versions of an application, it would be useful to filter tests by the minimum app version required to run it. 

Input files are referenced in `test.json` configuration files used by `nrtest`. Input files formats have a tendency to change slowly over time as features get added to an application. It would be useful to perform a check making sure that an input file is compatible with the version of the application executing it. This would help weed out false test failures related to input file format incompatibilities. 

This could be implemented by comparing the test version and app version tags when processing tests for execution.

### PR DESCRIPTION
**Pull request by davidchall**
Fixes #24

This adds a new optional field for the test config file: `minimum_app_version`. If the software is too old, then the test won't be executed or saved to the benchmark directory. For this reason, it is also ignored when comparing to other benchmarks.

This supports running an up-to-date testsuite on an old version of the software, without inevitably encountering test failures. This enables a more flexible workflow where a single testsuite can be maintained.

### CODE REVIEW

**Comment by davidchall** [comment]
Hi @michaeltryby - my hope is that this PR will support the workflow you were describing in https://github.com/davidchall/nrtest/issues/24. Are you able to checkout this PR to verify this?

If it all looks good, I can release this as v0.3.0 on PyPI.

**Comment by davidchall** [comment]
Hi @michaeltryby, I hope you're doing well? Does this PR meet the needs of the EPA?

**Comment by michaeltryby** [comment]
Hey @davidchall, This is precisely the feature I proposed in Issue #24.  I built the minimum_app_version branch and ran it and got the following output. 
```
(base) Z:\Desktop\SWC_QA\nrtests>python C:\tools\miniconda3\Scripts\nrtest execute apps\swmm-517w32.json tests\update_v5111 -o benchmark\testing
INFO: Skipping test (app version too old): "bioretention_cell"
Traceback (most recent call last):
  File "C:\tools\miniconda3\Scripts\nrtest", line 109, in <module>
    args.func(args)
  File "C:\tools\miniconda3\Scripts\nrtest", line 31, in execute
    if not validate_testsuite(ts):
  File "C:\tools\miniconda3\lib\site-packages\nrtest\execute.py", line 142, in validate_testsuite
    elif not validate_test(t):
  File "C:\tools\miniconda3\lib\site-packages\nrtest\execute.py", line 171, in validate_test
    if not os.path.isdir(p):
TypeError: _isdir: path should be string, bytes or os.PathLike, not NoneType
```
I am running Python 3.7 on Windows 10.

**Comment by davidchall** [comment]
@michaeltryby - ah, thank you so much for catching that! I've now resolved the issue, so it should work correctly now.

**Comment by michaeltryby** [comment]
Hey @davidchall, built the latest version of this branch and I am getting some strange behavior. I updated all the test.json files with minimum_app_version. All the tests should get skipped but some are still running. 

```
(base) Z:\Desktop\SWC_QA\nrtests>python C:\tools\miniconda3\Scripts\nrtest execute apps\swmm-517w32.json tests\update_v5111 -o benchmark\testing
INFO: Skipping test (app version too old): "bioretention_cell"
INFO: Skipping test (app version too old): "events_example"
INFO: Skipping test (app version too old): "porous pavement"
INFO: Found 6 tests
catchment_as_outfall: [31mfail[0m
catchment_as_outfall: Output file not generated: "catchment_as_outfall.out"
gate_control_3: [31mfail[0m
gate_control_3: Output file not generated: "gate_control_3.out"
rain_garden: [32mpass[0m
INFO: Finished
```
Running Python 3.7 on Windows 10

**Comment by davidchall** [comment]
I discovered a bug in this PR that relied on undefined behavior, which caused the sporadic failures you saw. I've fixed things up now.

I'm really sorry about these mistakes - this project is quite old and I don't have a great way to test things anymore.

**Comment by michaeltryby** [comment]
@davidchall No need to apologize. We really appreciate your continuing support of this package.

**Comment by michaeltryby** [comment]
@davidchall I built the latest version in this branch and made some runs. When a compare is performed and older and newer manifests get validated I am getting a value error exception that `minimum_app_version` field is missing. 

In my testing workflow I archive the reference benchmark for later use rather than executing a fresh one every time. Would it be possible to allow an older manifest without the field and a newer manifest with the field to be validated? 

Just treat a skipped test and a missing test. Make sense?

**Comment by davidchall** [comment]
@michaeltryby Ah yes, that makes a lot of sense. I've updated things so the output benchmarks aren't affected by this PR at all.

**Comment by michaeltryby** [comment]
@davidchall Built the latest version and everything seems to be working. Thanks!

**Comment by davidchall** [comment]
@michaeltryby - thanks for your patience! nrtest 0.2.5 is now on PyPI 🎉

**Pull request merged**
